### ISSUE TITLE
can't convert json to FIT ?

### ISSUE THREAD

**Issue by zed4** [philosowaffle/peloton-to-garmin#139] opened 2021-07-13 12:48 UTC
```
[08:44:03 ERR] Failed to convert workout data f8e013a7583c4177a0cb10a261922ce4_5_min_Post-Ride_Stretch_with_Sam_Yo ./working\downloaded\f8e013a7583c4177a0cb10a261922ce4_5_min_Post-Ride_Stretch_with_Sam_Yo.json
System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at Conversion.FitConverter.GetSessionMesg(Workout workout, WorkoutSamples workoutSamples, DateTime startTime, DateTime endTime, UInt16 numLaps) in D:\a\peloton-to-garmin\peloton-to-garmin\src\Conversion\FitConverter.cs:line 424
   at Conversion.FitConverter.Convert(Workout workout, WorkoutSamples workoutSamples) in D:\a\peloton-to-garmin\peloton-to-garmin\src\Conversion\FitConverter.cs:line 148
   at Conversion.Converter`1.Convert(String format) in D:\a\peloton-to-garmin\peloton-to-garmin\src\Conversion\IConverter.cs:line 90

```

**Installation (please complete the following information):**
 - OS: windows
 - Method: exe
 - Version: v2

**Additional context**
i was having this issue with v1, as well...
```
INFO:peloton-to-garmin:Processing f8e013a7583c4177a0cb10a261922ce4 : 5 min Post-Ride Stretch with Sam Yo (stretching) at Sun Jul 11 21:02:54 2021
ERROR:peloton-to-garmin.Tcx_Builder:Failed to Parse Speed/Cal/HR - Exception: 'NoneType' object is not subscriptable
ERROR:peloton-to-garmin:Failed to write TCX file for workout f8e013a7583c4177a0cb10a261922ce4 - Exception: cannot unpack non-iterable NoneType object
```

what is it looking for that it can no longer find? did peloton change the format of their json files?

**Comment by philosowaffle** [comment] 2021-07-13 13:02
Looks like a duplicate of #136 and #138

**Closed by philosowaffle** 2021-07-13 13:02 UTC
Labels: bug

**Comment by amy26point2** [comment] 2021-07-14 18:45
My meditation workouts seem to be getting stuck in the failed folder as .json files. 

2021-07-14 11:28:04.034 -05:00 [ERR] Failed to convert workout data 18d33d76e9a94f3bb1b3c1da18da420a_10_min_Peace_Meditation_with_Anna_Greenberg ./working/downloaded/18d33d76e9a94f3bb1b3c1da18da420a_10_min_Peace_Meditation_with_Anna_Greenberg.json
System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at Conversion.FitConverter.GetSessionMesg(Workout workout, WorkoutSamples workoutSamples, DateTime startTime, DateTime endTime, UInt16 numLaps) in /Users/amywenger/Downloads/peloton-to-garmin-master/src/Conversion/FitConverter.cs:line 421
   at Conversion.FitConverter.Convert(Workout workout, WorkoutSamples workoutSamples) in /Users/amywenger/Downloads/peloton-to-garmin-master/src/Conversion/FitConverter.cs:line 150
   at Conversion.Converter`1.Convert(String format) in /Users/amywenger/Downloads/peloton-to-garmin-master/src/Conversion/IConverter.cs:line 94
2021-07-14 11:28:04.076 -05:00 [INF] Encoded FIT file /Users/amywenger/Downloads/peloton-to-garmin-master/src/PelotonToGarminConsole/working/

OS: Mac
Method: Source
Version: 2.0.4

**Comment by amy26point2** [comment] 2021-07-16 22:33
Build 2.0.5 fixed my issue where meditation classes were failing to convert. Now if Garmin authentication would just cooperate so that they would automatically upload :)

**Comment by philosowaffle** [comment] 2021-07-19 22:45
@amy26point2 have you tried setting [Garmin.UploadStrategy](https://github.com/philosowaffle/peloton-to-garmin/wiki/Configuration#garmin-config) to `2`?
