### ISSUE TITLE
Issue with authentication to Garmin today.

### ISSUE THREAD

**Issue by rod-trent** [philosowaffle/peloton-to-garmin#528] opened 2023-09-26 15:13 UTC
**Describe the bug**
Issue with authentication to Garmin today.

**Error**
[11:10:56 ERR] Sync failed to authenticate with Garmin. Auth appeared successful but there was an error sending the service ticket.
Garmin.Auth.GarminAuthenticationError: Auth appeared successful but there was an error sending the service ticket.
 ---> Flurl.Http.FlurlHttpException: Circular redirects detected.
   at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Garmin.Auth.GarminAuthenticationService.CompleteGarminAuthenticationAsync(String loginResult, GarminApiAuthentication auth) in D:\a\peloton-to-garmin\peloton-to-garmin\src\Garmin\Auth\GarminAuthenticationService.cs:line 174
   --- End of inner exception stack trace ---
   at Garmin.Auth.GarminAuthenticationService.CompleteGarminAuthenticationAsync(String loginResult, GarminApiAuthentication auth) in D:\a\peloton-to-garmin\peloton-to-garmin\src\Garmin\Auth\GarminAuthenticationService.cs:line 181
   at Garmin.Auth.GarminAuthenticationService.RefreshGarminAuthenticationAsync() in D:\a\peloton-to-garmin\peloton-to-garmin\src\Garmin\Auth\GarminAuthenticationService.cs:line 146
   at Garmin.Auth.GarminAuthenticationService.GetGarminAuthenticationAsync() in D:\a\peloton-to-garmin\peloton-to-garmin\src\Garmin\Auth\GarminAuthenticationService.cs:line 70
   at Garmin.GarminUploader.UploadAsync(String[] files, Settings settings) in D:\a\peloton-to-garmin\peloton-to-garmin\src\Garmin\GarminUploader.cs:line 96
   at Garmin.GarminUploader.UploadToGarminAsync() in D:\a\peloton-to-garmin\peloton-to-garmin\src\Garmin\GarminUploader.cs:line 84
   at Sync.SyncService.SyncAsync(IEnumerable`1 workoutIds, ICollection`1 exclude) in D:\a\peloton-to-garmin\peloton-to-garmin\src\Sync\SyncService.cs:line 162

**Installation (please complete the following information):**
 - OS: [Windows]
 - Version: [latest version]

**Additional context**

**Comment by DevinTyler26** [comment] 2023-09-26 17:56
This is a duplicate of https://github.com/philosowaffle/peloton-to-garmin/issues/526

**Closed** 2023-09-26 22:35 UTC
Labels: bug
