### ISSUE TITLE
[Feature] Elevation on Runs

### ISSUE THREAD

**Issue by milleruk** [philosowaffle/peloton-to-garmin#668] opened 2024-10-20 20:50 UTC
**Is your feature request related to a problem? Please describe.**
Grab the elevation from a Tread workout so that it maps to Garmin - Happy for you to use my profile again as with the Guide metrics 

**Describe the solution you'd like**
Elevation is added so that The Total Ascent is shown in Garmin

**Comment by philosowaffle** [comment] 2024-10-26 13:39
Also related to #415

**Comment by philosowaffle** [comment] 2024-12-24 16:05
closing as duplicate of #476 - on the roadmap

**Closed by philosowaffle** 2024-12-24 16:05 UTC
Labels: enhancement
