### ISSUE TITLE
[CRITICAL] Login Failure: Authentification failed.

### ISSUE THREAD

**Issue by Isazcode** [philosowaffle/peloton-to-garmin#112] opened 2021-05-19 03:40 UTC
Trying to run the first version or V2 and still getting the same error message.

[CRITICAL] Login Failure: Authentification failed.
INFO - peloton-to-garmin: Failed to upload to Garmin. With error: Failed to authenticate garmin user.

Please how can I fix this?

Thank you

**Comment by chapinb** [comment] 2021-05-19 12:01
In the past this has been a temporary issue, that resolves on its own in a day or so. Unclear exactly why, though in the past I believe it was due to use of an unofficial Garmin API

**Comment by philosowaffle** [comment] 2021-05-19 13:15
Duplicate of #109 

Yes, Garmin does not provide a public API. We have to find workarounds in order to do the automated Garmin upload. Every now and then Garmin will change something related to authentication and it breaks our ability to authenticate with Garmin.  You can read more about this on the linked issue above.

**Closed by philosowaffle** 2021-05-19 13:15 UTC
