### ISSUE TITLE
Failing to download files due to API error

### ISSUE THREAD

**Issue by danielwollmann** [philosowaffle/peloton-to-garmin#56] opened 2020-12-16 23:14 UTC
How many past activities do you want to grab?  3
2020-12-16 15:12:32,916 - INFO - peloton-to-garmin: Get latest 3 workouts.
2020-12-16 15:12:33,281 - INFO - peloton-to-garmin: Get workout: 18753dcc467f4f63b9ff1f2c23d53de4
2020-12-16 15:12:33,603 - ERROR - peloton-to-garmin.Util: handle_error - Url: https://api.pelotoncycle.com/api/workout/18753dcc467f4f63b9ff1f2c23d53de4?joins=peloton,peloton.ride,peloton.ride.instructor,user
2020-12-16 15:12:33,604 - ERROR - peloton-to-garmin.Util: handle_error - Headers: {'User-Agent': 'python-requests/2.24.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Cookie': '__cfduid=d5f0dc5c1068ea762f9828845632af0c71608160349; __cfruid=9604582256407400d87e2b484078292b948a86ef-1608160352; peloton_session_id=1a11afe97dae47d3a86e04249efc46c3; peloton_session_id=1a11afe97dae47d3a86e04249efc46c3', 'Content-Length': '2', 'Content-Type': 'application/json'}

**Comment by philosowaffle** [comment] 2020-12-17 15:28
Duplicate of #46 

This has been resolved, please download the latest version of the code.

**Closed by philosowaffle** 2020-12-17 15:28 UTC
