### ISSUE TITLE
Failed to Parse Distance 

### ISSUE THREAD

**Issue by mahtani89** [philosowaffle/peloton-to-garmin#20] opened 2020-06-15 08:44 UTC
Hi there,

Firstly thanks so much for writing this amazing library, super helpful. Not sure if this has or is being addressed. I have set my peloton to record miles (as I saw that's what it needed to be on for this to work) how ever I get this error when running the script.

- Exception: list index out of range

**Comment by douglasawh** [comment] 2020-07-18 01:22
@mahtani89 Peloton in miles thing is not in the README.md. I assume you just found that in the code? Perhaps that explains https://connect.garmin.com/modern/activity/5252537906

I just submitted a PR for an updated README. Can you point me to the 'must be miles code'? I'll update the README again.

I might also go looking for it, but it probably won't be until mid-August until I have the time to dig in the code (I don't know python, though I can futz around)

**Comment by philosowaffle** [comment] 2020-07-22 20:06
@douglasawh the code that assumes Miles is [here](https://github.com/philosowaffle/peloton-to-garmin/blob/master/lib/tcx_builder.py#L24) and [here](https://github.com/philosowaffle/peloton-to-garmin/blob/master/lib/tcx_builder.py#L64).  When I first wrote the script I don't think I realized that Peloton let you configure how your distance is measured.  Gonna go ahead and close this per your suggestion as a duplicate of #15.

**Closed** 2020-07-22 20:06 UTC
Labels: duplicate
