### ISSUE TITLE
Selected workout doesnt synch to Garmin connect but indicates that it does 

### ISSUE THREAD

**Issue by Sewald001** [philosowaffle/peloton-to-garmin#685] opened 2024-11-26 23:13 UTC
**Describe the bug**
P2G confirms that seleceted workout was synched but nothing arrives in Connect 

**To Reproduce**
I select the workout that hasnt synched yet and hit synch -- Webui confirms that it was successfully synched yet nothing comes across

**Expected behavior**
Would expect the workout to appear in connect 

**Logs**
2024-11-27 00:07:40 [17:07:40 INF] Found 1 workouts remaining after filtering ExcludedWorkoutTypes.
2024-11-27 00:07:40 [17:07:40 INF] Converting workouts...
2024-11-27 00:07:40 info: Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor[1]
2024-11-27 00:07:40       Executing CreatedResult, writing value of type 'Api.Contract.SyncPostResponse'.
2024-11-27 00:07:40 info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[105]
2024-11-27 00:07:40       Executed action Api.Controllers.SyncController.SyncAsync (Api) in 2248.0666ms
2024-11-27 00:07:40 info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
2024-11-27 00:07:40       Executed endpoint 'Api.Controllers.SyncController.SyncAsync (Api)'
2024-11-27 00:07:40 info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
2024-11-27 00:07:40       Request finished HTTP/1.1 POST http://p2g-api:8080/api/sync application/json;+charset=UTF-8 51 - 201 - application/json;+charset=utf-8 2248.6484ms
Paste Log output here
```

**Installation (please complete the following information):**
 - OS: [mac]
 - Method: [docker]
 - Version: [4.3.0]

**Additional context**
I used it for over a year without problems and it stopped working -- I did a fresh install.  The UI seems to work fine and I dont get and error message either

**Comment by philosowaffle** [comment] 2024-11-27 14:29
Closing, duplicate of #683

**Closed by philosowaffle** 2024-11-27 14:29 UTC
Labels: bug
