### ISSUE TITLE
[Question] permissions issues on a folder

### ISSUE THREAD

**Issue by douglasawh** [philosowaffle/peloton-to-garmin#254] opened 2022-04-18 22:11 UTC
**Problem**
folder not written. If I write manually, it gets destroyed.

**Logs if applicable**

This for every single one.
```
[22:04:22 ERR] Failed to backup Fit file for 4305b6a3e2cb42e88d7e5d3f836e0bdf_140_min_29_sec_Just_Ride_with_JUST_RIDE
System.IO.DirectoryNotFoundException: Could not find a part of the path '/home/vagrant/downloadedSource/peloton-to-garmin/src/PelotonToGarminConsole/working/4305b6a3e2cb42e88d7e5d3f836e0bdf_140_min_29_sec_Just_Ride_with_JUST_RIDE.Fit'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at Common.IOWrapper.Copy(String from, String to, Boolean overwrite) in /home/vagrant/downloadedSource/peloton-to-garmin/src/Common/FileHandling.cs:line 122
   at Conversion.FitConverter.SaveLocalCopy(String sourcePath, String workoutTitle) in /home/vagrant/downloadedSource/peloton-to-garmin/src/Conversion/FitConverter.cs:line 58
   at Conversion.Converter`1.Convert(FileFormat format, P2GWorkout workoutData) in /home/vagrant/downloadedSource/peloton-to-garmin/src/Conversion/IConverter.cs:line 129
```

**Installation (please complete the following information):**
 - OS: [linux]
 - Method: [source]
 - Version: [2.0.2, I think...latest]

**Additional context**
Seems like the working directory is getting destroyed on run:   138  mkdir working
```
  139  cd ..
  140  dotnet run --project ./src/PelotonToGarminConsole/PelotonToGarminConsole.csproj
  141  ls /home/vagrant/downloadedSource/peloton-to-garmin/src/PelotonToGarminConsole/working
  142  ls /home/vagrant/downloadedSource/peloton-to-garmin/src/PelotonToGarminConsole/
  143  history

```

**Comment by douglasawh** [comment] 2022-04-19 00:36
Looks like the destruction is intended, so I guess that's not a clue. Or maybe it is and I just don't understand it yet.

```
[00:34:27 DBG] Deleting directory: /home/vagrant/downloadedSource/peloton-to-garmin/src/PelotonToGarminConsole/working/upload
[00:34:27 DBG] Deleting directory: /home/vagrant/downloadedSource/peloton-to-garmin/src/PelotonToGarminConsole/working
```

**Comment by douglasawh** [comment] 2022-04-19 00:45
Somehow I've gotten the issue to move forward. Not sure if it's worth a new issue. It might just be easiest to work with what I've got at this point. 

```
[00:41:31 ERR] Http Call Failed. Forbidden error code: 1020
[00:41:31 ERR] Authentication Failed.
Flurl.Http.FlurlHttpException: Call failed with status code 403 (Forbidden): POST https://sso.garmin.com/sso/signin?clientId=GarminConnect&consumeServiceTicket=false&createAccountShown=true&cssUrl=https%3A%2F%2Fstatic.garmincdn.com%2Fcom.garmin.connect%2Fui%2Fcss%2Fgauth-custom-v1.2-min.css&displayNameShown=false&embedWidget=false&gauthHost=https%3A%2F%2Fsso.garmin.com%2Fsso&generateExtraServiceTicket=false&id=gauth-widget&initialFocus=true&locale=en_US&openCreateAccount=false&redirectAfterAccountCreationUrl=https%3A%2F%2Fconnect.garmin.com%2F&redirectAfterAccountLoginUrl=https%3A%2F%2Fconnect.garmin.com%2F&rememberMeChecked=false&rememberMeShown=true&service=https%3A%2F%2Fconnect.garmin.com&source=https%3A%2F%2Fconnect.garmin.com&usernameShow=false&webhost=https%3A%2F%2Fconnect.garmin.com
   at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.ResponseExtensions.ReceiveString(Task`1 response)
   at Garmin.ApiClient.InitAuth() in /home/vagrant/downloadedSource/peloton-to-garmin/src/Garmin/ApiClient.cs:line 100
[00:41:31 ERR] Failed to upload workouts. GUpload had exit code of -2
[00:41:31 ERR] GUpload returned an error code. Failed to upload workouts.
Garmin.GarminUploadException: GUpload Exit Code: -2 - Failed to authenticate with Garmin.
 ---> Flurl.Http.FlurlHttpException: Call failed with status code 403 (Forbidden): POST https://sso.garmin.com/sso/signin?clientId=GarminConnect&consumeServiceTicket=false&createAccountShown=true&cssUrl=https%3A%2F%2Fstatic.garmincdn.com%2Fcom.garmin.connect%2Fui%2Fcss%2Fgauth-custom-v1.2-min.css&displayNameShown=false&embedWidget=false&gauthHost=https%3A%2F%2Fsso.garmin.com%2Fsso&generateExtraServiceTicket=false&id=gauth-widget&initialFocus=true&locale=en_US&openCreateAccount=false&redirectAfterAccountCreationUrl=https%3A%2F%2Fconnect.garmin.com%2F&redirectAfterAccountLoginUrl=https%3A%2F%2Fconnect.garmin.com%2F&rememberMeChecked=false&rememberMeShown=true&service=https%3A%2F%2Fconnect.garmin.com&source=https%3A%2F%2Fconnect.garmin.com&usernameShow=false&webhost=https%3A%2F%2Fconnect.garmin.com
   at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.ResponseExtensions.ReceiveString(Task`1 response)
   at Garmin.ApiClient.InitAuth() in /home/vagrant/downloadedSource/peloton-to-garmin/src/Garmin/ApiClient.cs:line 100
   at Garmin.GarminUploader.UploadAsync(String[] files) in /home/vagrant/downloadedSource/peloton-to-garmin/src/Garmin/GarminUploader.cs:line 88
   --- End of inner exception stack trace ---
   at Garmin.GarminUploader.UploadAsync(String[] files) in /home/vagrant/downloadedSource/peloton-to-garmin/src/Garmin/GarminUploader.cs:line 93
   at Garmin.GarminUploader.UploadToGarminAsync() in /home/vagrant/downloadedSource/peloton-to-garmin/src/Garmin/GarminUploader.cs:line 75
   at Sync.SyncService.SyncAsync(ICollection`1 workoutIds, ICollection`1 exclude) in /home/vagrant/downloadedSource/peloton-to-garmin/src/Sync/SyncService.cs:line 162
[00:41:31 WRN] GUpload failed to upload files. You can find the converted files at ./output
 You can manually upload your files to Garmin Connect, or wait for P2G to try again on the next sync job.
```

**Comment by philosowaffle** [comment] 2022-04-19 01:33
> System.IO.DirectoryNotFoundException: Could not find a part of the path ...

Root cause is a refactor I merged this morning: [commit](https://github.com/philosowaffle/peloton-to-garmin/commit/523120c068f0764d74bf1cabb862b18d370e461f#diff-a463e3069600be0d4092009949548b451273bb7759b3e14525e09ececfceafbeL70) that dropped the `MkDir` step.

BIt tricky to find actually because it takes a particular race condition to fall into this case. Fix is merged to master.

**Closed** 2022-04-19 01:33 UTC
