### ISSUE TITLE
Just started failing Garmin user login

### ISSUE THREAD

**Issue by WhatevsJJ** [philosowaffle/peloton-to-garmin#64] opened 2021-01-12 18:09 UTC
This is awesome and has worked for several weeks but started failing a few days ago.  Using same creds as defined in config.ini work at connect.garmin.com just fine.  But I get the error below when using the tool.

What am I doing wrong?

021-01-12 11:45:47,629 - INFO - peloton-to-garmin: Get latest 1 workouts.
2021-01-12 11:45:47,735 - INFO - peloton-to-garmin: Get workout: d87781e990a94724ac03dcc43b22a387
2021-01-12 11:45:47,968 - INFO - peloton-to-garmin: Get workout samples
2021-01-12 11:45:48,582 - INFO - peloton-to-garmin: Get workout summary
2021-01-12 11:45:50,764 - INFO - peloton-to-garmin: Writing TCX file: 1610378762-45 min 90s Ride with Emma Lovewell-d87781e990a94724ac03dcc43b22a387.tcx
2021-01-12 11:45:50,765 - INFO - peloton-to-garmin: Queing activity for upload: 45 min 90s Ride with Emma Lovewell
2021-01-12 11:45:50,766 - INFO - peloton-to-garmin: Uploading activities to Garmin...
2021-01-12 11:45:53,560 [CRITICAL] Login Failure: Login check failed.
Traceback (most recent call last):
  File "peloton-to-garmin.py", line 95, in <module>
    PelotonToGarmin.run(config)
  File "peloton-to-garmin.py", line 82, in run
    raise e
  File "peloton-to-garmin.py", line 79, in run
    garminUploader.uploadToGarmin(garminUploadHistoryTable)
  File "/data/programs/peloton-to-garmin/lib/garminClient.py", line 29, in uploadToGarmin
    assert self.user.authenticate(), "Failed to authenticate garmin user."
AssertionError: Failed to authenticate garmin user.

**Comment by philosowaffle** [comment] 2021-01-12 18:11
Duplicate of: https://github.com/philosowaffle/peloton-to-garmin/issues/62

Read through to end of thread for more info.

**Closed by philosowaffle** 2021-01-12 18:11 UTC

**Comment by WhatevsJJ** [comment] 2021-01-12 18:14
Dang, I knew I should have read the closed tickets - Thanks for the immediate reply!
Jason

**Comment by philosowaffle** [comment] 2021-01-12 18:22
lol np, its easy to reply immediately when I know what the issue is :P 

Just note, the problem is not 100% resolved for everyone yet, you'll see in the thread on that ticket what I mean.
