### ISSUE TITLE
Ampersands in title not escaped

### ISSUE THREAD

**Issue by geoffbon** [philosowaffle/peloton-to-garmin#621] opened 2024-01-24 23:49 UTC
**Describe the bug**
If a workout title contains an ampersand, e.g. `45 min HIIT & Hills Ride`, it transfers to Garmin as `&amp;`, e.g. `45 min HIIT &amp; Hills Ride`
![image](https://github.com/philosowaffle/peloton-to-garmin/assets/54509333/c2a9017d-8c5e-430f-ab31-fd4c8043e4c5)

**To Reproduce**
1. Ensure the title template includes the workout name
2. Sync any workout that contains an ampersand in the title

**Expected behavior**
The title should appear the same as in source workout name.

**Logs**

**Installation (please complete the following information):**
 - OS: windows
 - Method: exe
 - Version: 4.1.0

**Additional context**

**Comment by philosowaffle** [comment] 2024-01-27 10:53
Duplicate of #604 - fix will be in 4.2.0 once that get's released.  Might try to release it this weekend.

**Closed by philosowaffle** 2024-01-27 10:53 UTC
Labels: bug
